config/routes.rb
GyProject::Application.routes.draw do
  

  root to: "home#index"

  resources :totals

  resources :sueldos

  resources :subclases

  resources :ingresos

  resources :egresos

  resources :clases

  resources :proveedors

  resources :equipos

  resources :empleados

  resources :clientes

end

app/models/clase.rb
class Clase < ActiveRecord::Base
  attr_accessible :clases, :nombre, :nombre_prof, :profesor
end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
  attr_accessible :actividades, :apellido, :asistencia, :costo, :cuil, :direccion, :dni, :edad, :epicrisis, :fecha_ultimo_control, :mail, :medico_cabe, :medico_trat, :nacimiento, :nombre, :notas, :objetivos, :patologia, :sesiones, :tel_casa, :tel_emergencia, :tel_particular, :telefono_cabe, :telefono_trat, :vencimiento
end

app/models/egreso.rb
class Egreso < ActiveRecord::Base
  attr_accessible :art_limpieza, :beer_tan, :descripcion, :diario, :fecha, :monto, :nombre, :payes, :pepsico, :retiro_gus, :ro_golo, :tipo, :usuario, :varios
end

app/models/empleado.rb
class Empleado < ActiveRecord::Base
  attr_accessible :apellido, :capacitacion, :clases, :cuil, :direccion, :dni, :edad, :experiencia, :horarios, :horas_mes, :horas_mes_anterior, :mail, :mes, :nacimiento, :nombre, :notas, :observaciones, :porcentaje, :salario, :tel_casa, :tel_emergencia, :tel_particular, :valor_hora
end

app/models/equipo.rb
class Equipo < ActiveRecord::Base
  attr_accessible :descripcion, :fecha_proximo, :fecha_ultimo, :gasto, :nombre
end

app/models/ingreso.rb
class Ingreso < ActiveRecord::Base
  attr_accessible :bar, :cliente, :descripcion, :fecha, :monto, :nombre, :paleta, :pelota, :prot_grip, :turno
end

app/models/proveedor.rb
class Proveedor < ActiveRecord::Base
  attr_accessible :apellido, :cuil, :direccion, :mail, :nombre, :notas, :tel_casa, :tel_particular
end

app/models/subclase.rb
class Subclase < ActiveRecord::Base
  attr_accessible :alumnos, :dia, :hora_f, :hora_i, :nombre
end

app/models/sueldo.rb
class Sueldo < ActiveRecord::Base
  attr_accessible :fecha, :horas_trab, :pago
end

app/models/total.rb
class Total < ActiveRecord::Base
  attr_accessible :cancha, :gym, :nombre, :rehab
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  # GET /clientes
  # GET /clientes.json
  def index
    @clientes = Cliente.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @clientes }
    end
  end

  # GET /clientes/1
  # GET /clientes/1.json
  def show
    @cliente = Cliente.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cliente }
    end
  end

  # GET /clientes/new
  # GET /clientes/new.json
  def new
    @cliente = Cliente.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cliente }
    end
  end

  # GET /clientes/1/edit
  def edit
    @cliente = Cliente.find(params[:id])
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(params[:cliente])

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to @cliente, notice: 'Cliente was successfully created.' }
        format.json { render json: @cliente, status: :created, location: @cliente }
      else
        format.html { render action: "new" }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /clientes/1
  # PUT /clientes/1.json
  def update
    @cliente = Cliente.find(params[:id])

    respond_to do |format|
      if @cliente.update_attributes(params[:cliente])
        format.html { redirect_to @cliente, notice: 'Cliente was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    @cliente = Cliente.find(params[:id])
    @cliente.destroy

    respond_to do |format|
      format.html { redirect_to clientes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clases_helper.rb
module ClasesHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/egresos_helper.rb
module EgresosHelper
end

app/helpers/empleados_helper.rb
module EmpleadosHelper
end

app/helpers/equipos_helper.rb
module EquiposHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ingresos_helper.rb
module IngresosHelper
end

app/helpers/proveedors_helper.rb
module ProveedorsHelper
end

app/helpers/subclases_helper.rb
module SubclasesHelper
end

app/helpers/sueldos_helper.rb
module SueldosHelper
end

app/helpers/totals_helper.rb
module TotalsHelper
end

app/views/clientes/_form.html.erb
<%= form_for(@cliente) do |f| %>
  <% if @cliente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>

      <ul>
      <% @cliente.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :apellido %><br />
    <%= f.text_field :apellido %>
  </div>
  <div class="field">
    <%= f.label :dni %><br />
    <%= f.text_field :dni %>
  </div>
  <div class="field">
    <%= f.label :tel_casa %><br />
    <%= f.text_field :tel_casa %>
  </div>
  <div class="field">
    <%= f.label :tel_particular %><br />
    <%= f.text_field :tel_particular %>
  </div>
  <div class="field">
    <%= f.label :direccion %><br />
    <%= f.text_field :direccion %>
  </div>
  <div class="field">
    <%= f.label :mail %><br />
    <%= f.text_field :mail %>
  </div>
  <div class="field">
    <%= f.label :notas %><br />
    <%= f.text_field :notas %>
  </div>
  <div class="field">
    <%= f.label :edad %><br />
    <%= f.text_field :edad %>
  </div>
  <div class="field">
    <%= f.label :nacimiento %><br />
    <%= f.text_field :nacimiento %>
  </div>
  <div class="field">
    <%= f.label :cuil %><br />
    <%= f.text_field :cuil %>
  </div>
  <div class="field">
    <%= f.label :tel_emergencia %><br />
    <%= f.text_field :tel_emergencia %>
  </div>
  <div class="field">
    <%= f.label :medico_cabe %><br />
    <%= f.text_field :medico_cabe %>
  </div>
  <div class="field">
    <%= f.label :telefono_cabe %><br />
    <%= f.text_field :telefono_cabe %>
  </div>
  <div class="field">
    <%= f.label :medico_trat %><br />
    <%= f.text_field :medico_trat %>
  </div>
  <div class="field">
    <%= f.label :telefono_trat %><br />
    <%= f.text_field :telefono_trat %>
  </div>
  <div class="field">
    <%= f.label :fecha_ultimo_control %><br />
    <%= f.text_field :fecha_ultimo_control %>
  </div>
  <div class="field">
    <%= f.label :patologia %><br />
    <%= f.text_field :patologia %>
  </div>
  <div class="field">
    <%= f.label :actividades %><br />
    <%= f.text_field :actividades %>
  </div>
  <div class="field">
    <%= f.label :objetivos %><br />
    <%= f.text_field :objetivos %>
  </div>
  <div class="field">
    <%= f.label :epicrisis %><br />
    <%= f.text_field :epicrisis %>
  </div>
  <div class="field">
    <%= f.label :asistencia %><br />
    <%= f.text_field :asistencia %>
  </div>
  <div class="field">
    <%= f.label :vencimiento %><br />
    <%= f.text_field :vencimiento %>
  </div>
  <div class="field">
    <%= f.label :sesiones %><br />
    <%= f.text_field :sesiones %>
  </div>
  <div class="field">
    <%= f.label :costo %><br />
    <%= f.text_field :costo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clientes/edit.html.erb
<h1>Editing cliente</h1>

<%= render 'form' %>

<%= link_to 'Show', @cliente %> |
<%= link_to 'Back', clientes_path %>

app/views/clientes/index.html.erb
<h1>Listing clientes</h1>

<table>
  <tr>
    <th>Nombre</th>
    <th>Apellido</th>
    <th>Dni</th>
    <th>Tel casa</th>
    <th>Tel particular</th>
    <th>Direccion</th>
    <th>Mail</th>
    <th>Notas</th>
    <th>Edad</th>
    <th>Nacimiento</th>
    <th>Cuil</th>
    <th>Tel emergencia</th>
    <th>Medico cabe</th>
    <th>Telefono cabe</th>
    <th>Medico trat</th>
    <th>Telefono trat</th>
    <th>Fecha ultimo control</th>
    <th>Patologia</th>
    <th>Actividades</th>
    <th>Objetivos</th>
    <th>Epicrisis</th>
    <th>Asistencia</th>
    <th>Vencimiento</th>
    <th>Sesiones</th>
    <th>Costo</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @clientes.each do |cliente| %>
  <tr>
    <td><%= cliente.nombre %></td>
    <td><%= cliente.apellido %></td>
    <td><%= cliente.dni %></td>
    <td><%= cliente.tel_casa %></td>
    <td><%= cliente.tel_particular %></td>
    <td><%= cliente.direccion %></td>
    <td><%= cliente.mail %></td>
    <td><%= cliente.notas %></td>
    <td><%= cliente.edad %></td>
    <td><%= cliente.nacimiento %></td>
    <td><%= cliente.cuil %></td>
    <td><%= cliente.tel_emergencia %></td>
    <td><%= cliente.medico_cabe %></td>
    <td><%= cliente.telefono_cabe %></td>
    <td><%= cliente.medico_trat %></td>
    <td><%= cliente.telefono_trat %></td>
    <td><%= cliente.fecha_ultimo_control %></td>
    <td><%= cliente.patologia %></td>
    <td><%= cliente.actividades %></td>
    <td><%= cliente.objetivos %></td>
    <td><%= cliente.epicrisis %></td>
    <td><%= cliente.asistencia %></td>
    <td><%= cliente.vencimiento %></td>
    <td><%= cliente.sesiones %></td>
    <td><%= cliente.costo %></td>
    <td><%= link_to 'Show', cliente %></td>
    <td><%= link_to 'Edit', edit_cliente_path(cliente) %></td>
    <td><%= link_to 'Destroy', cliente, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cliente', new_cliente_path %>

app/views/clientes/new.html.erb
<h1>New cliente</h1>

<%= render 'form' %>

<%= link_to 'Back', clientes_path %>

app/views/clientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nombre:</b>
  <%= @cliente.nombre %>
</p>

<p>
  <b>Apellido:</b>
  <%= @cliente.apellido %>
</p>

<p>
  <b>Dni:</b>
  <%= @cliente.dni %>
</p>

<p>
  <b>Tel casa:</b>
  <%= @cliente.tel_casa %>
</p>

<p>
  <b>Tel particular:</b>
  <%= @cliente.tel_particular %>
</p>

<p>
  <b>Direccion:</b>
  <%= @cliente.direccion %>
</p>

<p>
  <b>Mail:</b>
  <%= @cliente.mail %>
</p>

<p>
  <b>Notas:</b>
  <%= @cliente.notas %>
</p>

<p>
  <b>Edad:</b>
  <%= @cliente.edad %>
</p>

<p>
  <b>Nacimiento:</b>
  <%= @cliente.nacimiento %>
</p>

<p>
  <b>Cuil:</b>
  <%= @cliente.cuil %>
</p>

<p>
  <b>Tel emergencia:</b>
  <%= @cliente.tel_emergencia %>
</p>

<p>
  <b>Medico cabe:</b>
  <%= @cliente.medico_cabe %>
</p>

<p>
  <b>Telefono cabe:</b>
  <%= @cliente.telefono_cabe %>
</p>

<p>
  <b>Medico trat:</b>
  <%= @cliente.medico_trat %>
</p>

<p>
  <b>Telefono trat:</b>
  <%= @cliente.telefono_trat %>
</p>

<p>
  <b>Fecha ultimo control:</b>
  <%= @cliente.fecha_ultimo_control %>
</p>

<p>
  <b>Patologia:</b>
  <%= @cliente.patologia %>
</p>

<p>
  <b>Actividades:</b>
  <%= @cliente.actividades %>
</p>

<p>
  <b>Objetivos:</b>
  <%= @cliente.objetivos %>
</p>

<p>
  <b>Epicrisis:</b>
  <%= @cliente.epicrisis %>
</p>

<p>
  <b>Asistencia:</b>
  <%= @cliente.asistencia %>
</p>

<p>
  <b>Vencimiento:</b>
  <%= @cliente.vencimiento %>
</p>

<p>
  <b>Sesiones:</b>
  <%= @cliente.sesiones %>
</p>

<p>
  <b>Costo:</b>
  <%= @cliente.costo %>
</p>


<%= link_to 'Edit', edit_cliente_path(@cliente) %> |
<%= link_to 'Back', clientes_path %>