config/routes.rb
GyProject::Application.routes.draw do
  

  root to: "home#index"

  resources :totals

  resources :sueldos

  resources :subclases

  resources :ingresos

  resources :egresos

  resources :clases

  resources :proveedors

  resources :equipos

  resources :empleados

  resources :clientes

end

app/models/clase.rb
class Clase < ActiveRecord::Base
  attr_accessible :clases, :nombre, :nombre_prof, :profesor
end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
  attr_accessible :actividades, :apellido, :asistencia, :costo, :cuil, :direccion, :dni, :edad, :epicrisis, :fecha_ultimo_control, :mail, :medico_cabe, :medico_trat, :nacimiento, :nombre, :notas, :objetivos, :patologia, :sesiones, :tel_casa, :tel_emergencia, :tel_particular, :telefono_cabe, :telefono_trat, :vencimiento
end

app/models/egreso.rb
class Egreso < ActiveRecord::Base
  attr_accessible :art_limpieza, :beer_tan, :descripcion, :diario, :fecha, :monto, :nombre, :payes, :pepsico, :retiro_gus, :ro_golo, :tipo, :usuario, :varios
end

app/models/empleado.rb
class Empleado < ActiveRecord::Base
  attr_accessible :apellido, :capacitacion, :clases, :cuil, :direccion, :dni, :edad, :experiencia, :horarios, :horas_mes, :horas_mes_anterior, :mail, :mes, :nacimiento, :nombre, :notas, :observaciones, :porcentaje, :salario, :tel_casa, :tel_emergencia, :tel_particular, :valor_hora
end

app/models/equipo.rb
class Equipo < ActiveRecord::Base
  attr_accessible :descripcion, :fecha_proximo, :fecha_ultimo, :gasto, :nombre
end

app/models/ingreso.rb
class Ingreso < ActiveRecord::Base
  attr_accessible :bar, :cliente, :descripcion, :fecha, :monto, :nombre, :paleta, :pelota, :prot_grip, :turno
end

app/models/proveedor.rb
class Proveedor < ActiveRecord::Base
  attr_accessible :apellido, :cuil, :direccion, :mail, :nombre, :notas, :tel_casa, :tel_particular
end

app/models/subclase.rb
class Subclase < ActiveRecord::Base
  attr_accessible :alumnos, :dia, :hora_f, :hora_i, :nombre
end

app/models/sueldo.rb
class Sueldo < ActiveRecord::Base
  attr_accessible :fecha, :horas_trab, :pago
end

app/models/total.rb
class Total < ActiveRecord::Base
  attr_accessible :cancha, :gym, :nombre, :rehab
end

app/controllers/egresos_controller.rb
class EgresosController < ApplicationController
  # GET /egresos
  # GET /egresos.json
  def index
    @egresos = Egreso.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @egresos }
    end
  end

  # GET /egresos/1
  # GET /egresos/1.json
  def show
    @egreso = Egreso.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @egreso }
    end
  end

  # GET /egresos/new
  # GET /egresos/new.json
  def new
    @egreso = Egreso.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @egreso }
    end
  end

  # GET /egresos/1/edit
  def edit
    @egreso = Egreso.find(params[:id])
  end

  # POST /egresos
  # POST /egresos.json
  def create
    @egreso = Egreso.new(params[:egreso])

    respond_to do |format|
      if @egreso.save
        format.html { redirect_to @egreso, notice: 'Egreso was successfully created.' }
        format.json { render json: @egreso, status: :created, location: @egreso }
      else
        format.html { render action: "new" }
        format.json { render json: @egreso.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /egresos/1
  # PUT /egresos/1.json
  def update
    @egreso = Egreso.find(params[:id])

    respond_to do |format|
      if @egreso.update_attributes(params[:egreso])
        format.html { redirect_to @egreso, notice: 'Egreso was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @egreso.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /egresos/1
  # DELETE /egresos/1.json
  def destroy
    @egreso = Egreso.find(params[:id])
    @egreso.destroy

    respond_to do |format|
      format.html { redirect_to egresos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clases_helper.rb
module ClasesHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/egresos_helper.rb
module EgresosHelper
end

app/helpers/empleados_helper.rb
module EmpleadosHelper
end

app/helpers/equipos_helper.rb
module EquiposHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ingresos_helper.rb
module IngresosHelper
end

app/helpers/proveedors_helper.rb
module ProveedorsHelper
end

app/helpers/subclases_helper.rb
module SubclasesHelper
end

app/helpers/sueldos_helper.rb
module SueldosHelper
end

app/helpers/totals_helper.rb
module TotalsHelper
end

app/views/egresos/_form.html.erb
<%= form_for(@egreso) do |f| %>
  <% if @egreso.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@egreso.errors.count, "error") %> prohibited this egreso from being saved:</h2>

      <ul>
      <% @egreso.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br />
    <%= f.text_field :descripcion %>
  </div>
  <div class="field">
    <%= f.label :tipo %><br />
    <%= f.text_field :tipo %>
  </div>
  <div class="field">
    <%= f.label :monto %><br />
    <%= f.text_field :monto %>
  </div>
  <div class="field">
    <%= f.label :diario %><br />
    <%= f.text_field :diario %>
  </div>
  <div class="field">
    <%= f.label :beer_tan %><br />
    <%= f.text_field :beer_tan %>
  </div>
  <div class="field">
    <%= f.label :pepsico %><br />
    <%= f.text_field :pepsico %>
  </div>
  <div class="field">
    <%= f.label :ro_golo %><br />
    <%= f.text_field :ro_golo %>
  </div>
  <div class="field">
    <%= f.label :payes %><br />
    <%= f.text_field :payes %>
  </div>
  <div class="field">
    <%= f.label :art_limpieza %><br />
    <%= f.text_field :art_limpieza %>
  </div>
  <div class="field">
    <%= f.label :varios %><br />
    <%= f.text_field :varios %>
  </div>
  <div class="field">
    <%= f.label :retiro_gus %><br />
    <%= f.text_field :retiro_gus %>
  </div>
  <div class="field">
    <%= f.label :fecha %><br />
    <%= f.text_field :fecha %>
  </div>
  <div class="field">
    <%= f.label :usuario %><br />
    <%= f.text_field :usuario %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/egresos/edit.html.erb
<h1>Editing egreso</h1>

<%= render 'form' %>

<%= link_to 'Show', @egreso %> |
<%= link_to 'Back', egresos_path %>

app/views/egresos/index.html.erb
<h1>Listing egresos</h1>

<table>
  <tr>
    <th>Nombre</th>
    <th>Descripcion</th>
    <th>Tipo</th>
    <th>Monto</th>
    <th>Diario</th>
    <th>Beer tan</th>
    <th>Pepsico</th>
    <th>Ro golo</th>
    <th>Payes</th>
    <th>Art limpieza</th>
    <th>Varios</th>
    <th>Retiro gus</th>
    <th>Fecha</th>
    <th>Usuario</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @egresos.each do |egreso| %>
  <tr>
    <td><%= egreso.nombre %></td>
    <td><%= egreso.descripcion %></td>
    <td><%= egreso.tipo %></td>
    <td><%= egreso.monto %></td>
    <td><%= egreso.diario %></td>
    <td><%= egreso.beer_tan %></td>
    <td><%= egreso.pepsico %></td>
    <td><%= egreso.ro_golo %></td>
    <td><%= egreso.payes %></td>
    <td><%= egreso.art_limpieza %></td>
    <td><%= egreso.varios %></td>
    <td><%= egreso.retiro_gus %></td>
    <td><%= egreso.fecha %></td>
    <td><%= egreso.usuario %></td>
    <td><%= link_to 'Show', egreso %></td>
    <td><%= link_to 'Edit', edit_egreso_path(egreso) %></td>
    <td><%= link_to 'Destroy', egreso, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Egreso', new_egreso_path %>

app/views/egresos/new.html.erb
<h1>New egreso</h1>

<%= render 'form' %>

<%= link_to 'Back', egresos_path %>

app/views/egresos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nombre:</b>
  <%= @egreso.nombre %>
</p>

<p>
  <b>Descripcion:</b>
  <%= @egreso.descripcion %>
</p>

<p>
  <b>Tipo:</b>
  <%= @egreso.tipo %>
</p>

<p>
  <b>Monto:</b>
  <%= @egreso.monto %>
</p>

<p>
  <b>Diario:</b>
  <%= @egreso.diario %>
</p>

<p>
  <b>Beer tan:</b>
  <%= @egreso.beer_tan %>
</p>

<p>
  <b>Pepsico:</b>
  <%= @egreso.pepsico %>
</p>

<p>
  <b>Ro golo:</b>
  <%= @egreso.ro_golo %>
</p>

<p>
  <b>Payes:</b>
  <%= @egreso.payes %>
</p>

<p>
  <b>Art limpieza:</b>
  <%= @egreso.art_limpieza %>
</p>

<p>
  <b>Varios:</b>
  <%= @egreso.varios %>
</p>

<p>
  <b>Retiro gus:</b>
  <%= @egreso.retiro_gus %>
</p>

<p>
  <b>Fecha:</b>
  <%= @egreso.fecha %>
</p>

<p>
  <b>Usuario:</b>
  <%= @egreso.usuario %>
</p>


<%= link_to 'Edit', edit_egreso_path(@egreso) %> |
<%= link_to 'Back', egresos_path %>