config/routes.rb
GyProject::Application.routes.draw do
  

  root to: "home#index"

  resources :totals

  resources :sueldos

  resources :subclases

  resources :ingresos

  resources :egresos

  resources :clases

  resources :proveedors

  resources :equipos

  resources :empleados

  resources :clientes

end

app/models/clase.rb
class Clase < ActiveRecord::Base
  attr_accessible :clases, :nombre, :nombre_prof, :profesor
end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
  attr_accessible :actividades, :apellido, :asistencia, :costo, :cuil, :direccion, :dni, :edad, :epicrisis, :fecha_ultimo_control, :mail, :medico_cabe, :medico_trat, :nacimiento, :nombre, :notas, :objetivos, :patologia, :sesiones, :tel_casa, :tel_emergencia, :tel_particular, :telefono_cabe, :telefono_trat, :vencimiento
end

app/models/egreso.rb
class Egreso < ActiveRecord::Base
  attr_accessible :art_limpieza, :beer_tan, :descripcion, :diario, :fecha, :monto, :nombre, :payes, :pepsico, :retiro_gus, :ro_golo, :tipo, :usuario, :varios
end

app/models/empleado.rb
class Empleado < ActiveRecord::Base
  attr_accessible :apellido, :capacitacion, :clases, :cuil, :direccion, :dni, :edad, :experiencia, :horarios, :horas_mes, :horas_mes_anterior, :mail, :mes, :nacimiento, :nombre, :notas, :observaciones, :porcentaje, :salario, :tel_casa, :tel_emergencia, :tel_particular, :valor_hora
end

app/models/equipo.rb
class Equipo < ActiveRecord::Base
  attr_accessible :descripcion, :fecha_proximo, :fecha_ultimo, :gasto, :nombre
end

app/models/ingreso.rb
class Ingreso < ActiveRecord::Base
  attr_accessible :bar, :cliente, :descripcion, :fecha, :monto, :nombre, :paleta, :pelota, :prot_grip, :turno
end

app/models/proveedor.rb
class Proveedor < ActiveRecord::Base
  attr_accessible :apellido, :cuil, :direccion, :mail, :nombre, :notas, :tel_casa, :tel_particular
end

app/models/subclase.rb
class Subclase < ActiveRecord::Base
  attr_accessible :alumnos, :dia, :hora_f, :hora_i, :nombre
end

app/models/sueldo.rb
class Sueldo < ActiveRecord::Base
  attr_accessible :fecha, :horas_trab, :pago
end

app/models/total.rb
class Total < ActiveRecord::Base
  attr_accessible :cancha, :gym, :nombre, :rehab
end

app/controllers/ingresos_controller.rb
class IngresosController < ApplicationController
  # GET /ingresos
  # GET /ingresos.json
  def index
    @ingresos = Ingreso.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ingresos }
    end
  end

  # GET /ingresos/1
  # GET /ingresos/1.json
  def show
    @ingreso = Ingreso.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ingreso }
    end
  end

  # GET /ingresos/new
  # GET /ingresos/new.json
  def new
    @ingreso = Ingreso.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ingreso }
    end
  end

  # GET /ingresos/1/edit
  def edit
    @ingreso = Ingreso.find(params[:id])
  end

  # POST /ingresos
  # POST /ingresos.json
  def create
    @ingreso = Ingreso.new(params[:ingreso])

    respond_to do |format|
      if @ingreso.save
        format.html { redirect_to @ingreso, notice: 'Ingreso was successfully created.' }
        format.json { render json: @ingreso, status: :created, location: @ingreso }
      else
        format.html { render action: "new" }
        format.json { render json: @ingreso.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ingresos/1
  # PUT /ingresos/1.json
  def update
    @ingreso = Ingreso.find(params[:id])

    respond_to do |format|
      if @ingreso.update_attributes(params[:ingreso])
        format.html { redirect_to @ingreso, notice: 'Ingreso was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ingreso.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingresos/1
  # DELETE /ingresos/1.json
  def destroy
    @ingreso = Ingreso.find(params[:id])
    @ingreso.destroy

    respond_to do |format|
      format.html { redirect_to ingresos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clases_helper.rb
module ClasesHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/egresos_helper.rb
module EgresosHelper
end

app/helpers/empleados_helper.rb
module EmpleadosHelper
end

app/helpers/equipos_helper.rb
module EquiposHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ingresos_helper.rb
module IngresosHelper
end

app/helpers/proveedors_helper.rb
module ProveedorsHelper
end

app/helpers/subclases_helper.rb
module SubclasesHelper
end

app/helpers/sueldos_helper.rb
module SueldosHelper
end

app/helpers/totals_helper.rb
module TotalsHelper
end

app/views/ingresos/_form.html.erb
<%= form_for(@ingreso) do |f| %>
  <% if @ingreso.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ingreso.errors.count, "error") %> prohibited this ingreso from being saved:</h2>

      <ul>
      <% @ingreso.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br />
    <%= f.text_field :descripcion %>
  </div>
  <div class="field">
    <%= f.label :monto %><br />
    <%= f.text_field :monto %>
  </div>
  <div class="field">
    <%= f.label :turno %><br />
    <%= f.text_field :turno %>
  </div>
  <div class="field">
    <%= f.label :bar %><br />
    <%= f.text_field :bar %>
  </div>
  <div class="field">
    <%= f.label :paleta %><br />
    <%= f.text_field :paleta %>
  </div>
  <div class="field">
    <%= f.label :prot_grip %><br />
    <%= f.text_field :prot_grip %>
  </div>
  <div class="field">
    <%= f.label :pelota %><br />
    <%= f.text_field :pelota %>
  </div>
  <div class="field">
    <%= f.label :fecha %><br />
    <%= f.text_field :fecha %>
  </div>
  <div class="field">
    <%= f.label :cliente %><br />
    <%= f.text_field :cliente %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ingresos/edit.html.erb
<h1>Editing ingreso</h1>

<%= render 'form' %>

<%= link_to 'Show', @ingreso %> |
<%= link_to 'Back', ingresos_path %>

app/views/ingresos/index.html.erb
<h1>Listing ingresos</h1>

<table>
  <tr>
    <th>Nombre</th>
    <th>Descripcion</th>
    <th>Monto</th>
    <th>Turno</th>
    <th>Bar</th>
    <th>Paleta</th>
    <th>Prot grip</th>
    <th>Pelota</th>
    <th>Fecha</th>
    <th>Cliente</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ingresos.each do |ingreso| %>
  <tr>
    <td><%= ingreso.nombre %></td>
    <td><%= ingreso.descripcion %></td>
    <td><%= ingreso.monto %></td>
    <td><%= ingreso.turno %></td>
    <td><%= ingreso.bar %></td>
    <td><%= ingreso.paleta %></td>
    <td><%= ingreso.prot_grip %></td>
    <td><%= ingreso.pelota %></td>
    <td><%= ingreso.fecha %></td>
    <td><%= ingreso.cliente %></td>
    <td><%= link_to 'Show', ingreso %></td>
    <td><%= link_to 'Edit', edit_ingreso_path(ingreso) %></td>
    <td><%= link_to 'Destroy', ingreso, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Ingreso', new_ingreso_path %>

app/views/ingresos/new.html.erb
<h1>New ingreso</h1>

<%= render 'form' %>

<%= link_to 'Back', ingresos_path %>

app/views/ingresos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nombre:</b>
  <%= @ingreso.nombre %>
</p>

<p>
  <b>Descripcion:</b>
  <%= @ingreso.descripcion %>
</p>

<p>
  <b>Monto:</b>
  <%= @ingreso.monto %>
</p>

<p>
  <b>Turno:</b>
  <%= @ingreso.turno %>
</p>

<p>
  <b>Bar:</b>
  <%= @ingreso.bar %>
</p>

<p>
  <b>Paleta:</b>
  <%= @ingreso.paleta %>
</p>

<p>
  <b>Prot grip:</b>
  <%= @ingreso.prot_grip %>
</p>

<p>
  <b>Pelota:</b>
  <%= @ingreso.pelota %>
</p>

<p>
  <b>Fecha:</b>
  <%= @ingreso.fecha %>
</p>

<p>
  <b>Cliente:</b>
  <%= @ingreso.cliente %>
</p>


<%= link_to 'Edit', edit_ingreso_path(@ingreso) %> |
<%= link_to 'Back', ingresos_path %>