config/routes.rb
GyProject::Application.routes.draw do
  

  root to: "home#index"

  resources :totals

  resources :sueldos

  resources :subclases

  resources :ingresos

  resources :egresos

  resources :clases

  resources :proveedors

  resources :equipos

  resources :empleados

  resources :clientes

end

app/models/clase.rb
class Clase < ActiveRecord::Base
  attr_accessible :clases, :nombre, :nombre_prof, :profesor
end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
  attr_accessible :actividades, :apellido, :asistencia, :costo, :cuil, :direccion, :dni, :edad, :epicrisis, :fecha_ultimo_control, :mail, :medico_cabe, :medico_trat, :nacimiento, :nombre, :notas, :objetivos, :patologia, :sesiones, :tel_casa, :tel_emergencia, :tel_particular, :telefono_cabe, :telefono_trat, :vencimiento
end

app/models/egreso.rb
class Egreso < ActiveRecord::Base
  attr_accessible :art_limpieza, :beer_tan, :descripcion, :diario, :fecha, :monto, :nombre, :payes, :pepsico, :retiro_gus, :ro_golo, :tipo, :usuario, :varios
end

app/models/empleado.rb
class Empleado < ActiveRecord::Base
  attr_accessible :apellido, :capacitacion, :clases, :cuil, :direccion, :dni, :edad, :experiencia, :horarios, :horas_mes, :horas_mes_anterior, :mail, :mes, :nacimiento, :nombre, :notas, :observaciones, :porcentaje, :salario, :tel_casa, :tel_emergencia, :tel_particular, :valor_hora
end

app/models/equipo.rb
class Equipo < ActiveRecord::Base
  attr_accessible :descripcion, :fecha_proximo, :fecha_ultimo, :gasto, :nombre
end

app/models/ingreso.rb
class Ingreso < ActiveRecord::Base
  attr_accessible :bar, :cliente, :descripcion, :fecha, :monto, :nombre, :paleta, :pelota, :prot_grip, :turno
end

app/models/proveedor.rb
class Proveedor < ActiveRecord::Base
  attr_accessible :apellido, :cuil, :direccion, :mail, :nombre, :notas, :tel_casa, :tel_particular
end

app/models/subclase.rb
class Subclase < ActiveRecord::Base
  attr_accessible :alumnos, :dia, :hora_f, :hora_i, :nombre
end

app/models/sueldo.rb
class Sueldo < ActiveRecord::Base
  attr_accessible :fecha, :horas_trab, :pago
end

app/models/total.rb
class Total < ActiveRecord::Base
  attr_accessible :cancha, :gym, :nombre, :rehab
end

app/controllers/empleados_controller.rb
class EmpleadosController < ApplicationController
  # GET /empleados
  # GET /empleados.json
  def index
    @empleados = Empleado.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @empleados }
    end
  end

  # GET /empleados/1
  # GET /empleados/1.json
  def show
    @empleado = Empleado.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @empleado }
    end
  end

  # GET /empleados/new
  # GET /empleados/new.json
  def new
    @empleado = Empleado.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @empleado }
    end
  end

  # GET /empleados/1/edit
  def edit
    @empleado = Empleado.find(params[:id])
  end

  # POST /empleados
  # POST /empleados.json
  def create
    @empleado = Empleado.new(params[:empleado])

    respond_to do |format|
      if @empleado.save
        format.html { redirect_to @empleado, notice: 'Empleado was successfully created.' }
        format.json { render json: @empleado, status: :created, location: @empleado }
      else
        format.html { render action: "new" }
        format.json { render json: @empleado.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /empleados/1
  # PUT /empleados/1.json
  def update
    @empleado = Empleado.find(params[:id])

    respond_to do |format|
      if @empleado.update_attributes(params[:empleado])
        format.html { redirect_to @empleado, notice: 'Empleado was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @empleado.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /empleados/1
  # DELETE /empleados/1.json
  def destroy
    @empleado = Empleado.find(params[:id])
    @empleado.destroy

    respond_to do |format|
      format.html { redirect_to empleados_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clases_helper.rb
module ClasesHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/egresos_helper.rb
module EgresosHelper
end

app/helpers/empleados_helper.rb
module EmpleadosHelper
end

app/helpers/equipos_helper.rb
module EquiposHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ingresos_helper.rb
module IngresosHelper
end

app/helpers/proveedors_helper.rb
module ProveedorsHelper
end

app/helpers/subclases_helper.rb
module SubclasesHelper
end

app/helpers/sueldos_helper.rb
module SueldosHelper
end

app/helpers/totals_helper.rb
module TotalsHelper
end

app/views/empleados/_form.html.erb
<%= form_for(@empleado) do |f| %>
  <% if @empleado.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@empleado.errors.count, "error") %> prohibited this empleado from being saved:</h2>

      <ul>
      <% @empleado.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :apellido %><br />
    <%= f.text_field :apellido %>
  </div>
  <div class="field">
    <%= f.label :dni %><br />
    <%= f.text_field :dni %>
  </div>
  <div class="field">
    <%= f.label :tel_casa %><br />
    <%= f.text_field :tel_casa %>
  </div>
  <div class="field">
    <%= f.label :tel_particular %><br />
    <%= f.text_field :tel_particular %>
  </div>
  <div class="field">
    <%= f.label :direccion %><br />
    <%= f.text_field :direccion %>
  </div>
  <div class="field">
    <%= f.label :mail %><br />
    <%= f.text_field :mail %>
  </div>
  <div class="field">
    <%= f.label :notas %><br />
    <%= f.text_field :notas %>
  </div>
  <div class="field">
    <%= f.label :capacitacion %><br />
    <%= f.text_field :capacitacion %>
  </div>
  <div class="field">
    <%= f.label :experiencia %><br />
    <%= f.text_field :experiencia %>
  </div>
  <div class="field">
    <%= f.label :horarios %><br />
    <%= f.text_field :horarios %>
  </div>
  <div class="field">
    <%= f.label :observaciones %><br />
    <%= f.text_field :observaciones %>
  </div>
  <div class="field">
    <%= f.label :edad %><br />
    <%= f.text_field :edad %>
  </div>
  <div class="field">
    <%= f.label :nacimiento %><br />
    <%= f.text_field :nacimiento %>
  </div>
  <div class="field">
    <%= f.label :cuil %><br />
    <%= f.text_field :cuil %>
  </div>
  <div class="field">
    <%= f.label :tel_emergencia %><br />
    <%= f.text_field :tel_emergencia %>
  </div>
  <div class="field">
    <%= f.label :valor_hora %><br />
    <%= f.text_field :valor_hora %>
  </div>
  <div class="field">
    <%= f.label :horas_mes %><br />
    <%= f.text_field :horas_mes %>
  </div>
  <div class="field">
    <%= f.label :horas_mes_anterior %><br />
    <%= f.text_field :horas_mes_anterior %>
  </div>
  <div class="field">
    <%= f.label :porcentaje %><br />
    <%= f.text_field :porcentaje %>
  </div>
  <div class="field">
    <%= f.label :mes %><br />
    <%= f.text_field :mes %>
  </div>
  <div class="field">
    <%= f.label :clases %><br />
    <%= f.text_field :clases %>
  </div>
  <div class="field">
    <%= f.label :salario %><br />
    <%= f.text_field :salario %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/empleados/edit.html.erb
<h1>Editing empleado</h1>

<%= render 'form' %>

<%= link_to 'Show', @empleado %> |
<%= link_to 'Back', empleados_path %>

app/views/empleados/index.html.erb
<h1>Listing empleados</h1>

<table>
  <tr>
    <th>Nombre</th>
    <th>Apellido</th>
    <th>Dni</th>
    <th>Tel casa</th>
    <th>Tel particular</th>
    <th>Direccion</th>
    <th>Mail</th>
    <th>Notas</th>
    <th>Capacitacion</th>
    <th>Experiencia</th>
    <th>Horarios</th>
    <th>Observaciones</th>
    <th>Edad</th>
    <th>Nacimiento</th>
    <th>Cuil</th>
    <th>Tel emergencia</th>
    <th>Valor hora</th>
    <th>Horas mes</th>
    <th>Horas mes anterior</th>
    <th>Porcentaje</th>
    <th>Mes</th>
    <th>Clases</th>
    <th>Salario</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @empleados.each do |empleado| %>
  <tr>
    <td><%= empleado.nombre %></td>
    <td><%= empleado.apellido %></td>
    <td><%= empleado.dni %></td>
    <td><%= empleado.tel_casa %></td>
    <td><%= empleado.tel_particular %></td>
    <td><%= empleado.direccion %></td>
    <td><%= empleado.mail %></td>
    <td><%= empleado.notas %></td>
    <td><%= empleado.capacitacion %></td>
    <td><%= empleado.experiencia %></td>
    <td><%= empleado.horarios %></td>
    <td><%= empleado.observaciones %></td>
    <td><%= empleado.edad %></td>
    <td><%= empleado.nacimiento %></td>
    <td><%= empleado.cuil %></td>
    <td><%= empleado.tel_emergencia %></td>
    <td><%= empleado.valor_hora %></td>
    <td><%= empleado.horas_mes %></td>
    <td><%= empleado.horas_mes_anterior %></td>
    <td><%= empleado.porcentaje %></td>
    <td><%= empleado.mes %></td>
    <td><%= empleado.clases %></td>
    <td><%= empleado.salario %></td>
    <td><%= link_to 'Show', empleado %></td>
    <td><%= link_to 'Edit', edit_empleado_path(empleado) %></td>
    <td><%= link_to 'Destroy', empleado, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Empleado', new_empleado_path %>

app/views/empleados/new.html.erb
<h1>New empleado</h1>

<%= render 'form' %>

<%= link_to 'Back', empleados_path %>

app/views/empleados/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nombre:</b>
  <%= @empleado.nombre %>
</p>

<p>
  <b>Apellido:</b>
  <%= @empleado.apellido %>
</p>

<p>
  <b>Dni:</b>
  <%= @empleado.dni %>
</p>

<p>
  <b>Tel casa:</b>
  <%= @empleado.tel_casa %>
</p>

<p>
  <b>Tel particular:</b>
  <%= @empleado.tel_particular %>
</p>

<p>
  <b>Direccion:</b>
  <%= @empleado.direccion %>
</p>

<p>
  <b>Mail:</b>
  <%= @empleado.mail %>
</p>

<p>
  <b>Notas:</b>
  <%= @empleado.notas %>
</p>

<p>
  <b>Capacitacion:</b>
  <%= @empleado.capacitacion %>
</p>

<p>
  <b>Experiencia:</b>
  <%= @empleado.experiencia %>
</p>

<p>
  <b>Horarios:</b>
  <%= @empleado.horarios %>
</p>

<p>
  <b>Observaciones:</b>
  <%= @empleado.observaciones %>
</p>

<p>
  <b>Edad:</b>
  <%= @empleado.edad %>
</p>

<p>
  <b>Nacimiento:</b>
  <%= @empleado.nacimiento %>
</p>

<p>
  <b>Cuil:</b>
  <%= @empleado.cuil %>
</p>

<p>
  <b>Tel emergencia:</b>
  <%= @empleado.tel_emergencia %>
</p>

<p>
  <b>Valor hora:</b>
  <%= @empleado.valor_hora %>
</p>

<p>
  <b>Horas mes:</b>
  <%= @empleado.horas_mes %>
</p>

<p>
  <b>Horas mes anterior:</b>
  <%= @empleado.horas_mes_anterior %>
</p>

<p>
  <b>Porcentaje:</b>
  <%= @empleado.porcentaje %>
</p>

<p>
  <b>Mes:</b>
  <%= @empleado.mes %>
</p>

<p>
  <b>Clases:</b>
  <%= @empleado.clases %>
</p>

<p>
  <b>Salario:</b>
  <%= @empleado.salario %>
</p>


<%= link_to 'Edit', edit_empleado_path(@empleado) %> |
<%= link_to 'Back', empleados_path %>